server:
  port: 8081

spring:
  application:
    name: kafka-consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: kafka-study-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 3
